---
- name: Add Vector APT repository
  apt_key:
    url: https://repositories.timber.io/public/vector/gpg.4B154D6C0B1B9B8F.key
    state: present
  become: true

- name: Add Vector repo to sources list
  apt_repository:
    repo: "deb https://repositories.timber.io/public/vector/deb/debian any-version main"
    state: present
    filename: vector
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Ensure vector is installed
  apt:
    name: vector
    state: present
  become: true

- name: Ensure vector is installed
  apt:
    name: vector
    state: present
  become: true

- name: Create data directory
  file:
    path: "{{ vector_data_dir }}"
    state: directory
    owner: vector
    group: vector
    mode: '0755'
  become: true

- name: Deploy vector config
  template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    owner: vector
    group: vector
    mode: '0644'
  notify: Restart vector
  become: true

- name: Ensure vector is running and enabled
  systemd:
    name: vector
    state: started
    enabled: true
  become: true
