---
- name: Download Vector GPG key (Debian Bookworm)
  ansible.builtin.get_url:
    url: https://apt.vector.dev/vector.asc
    dest: /usr/share/keyrings/vector-archive-keyring.gpg
    mode: '0644'
  become: true

- name: Add Vector APT repo for Debian 12 (Bookworm)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/vector-archive-keyring.gpg] https://apt.vector.dev/ debian bookworm main"
    state: present
    filename: vector
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install vector
  ansible.builtin.apt:
    name: vector
    state: present
  become: true

- name: Ensure vector is installed
  apt:
    name: vector
    state: present
  become: true

- name: Ensure vector is installed
  apt:
    name: vector
    state: present
  become: true

- name: Create data directory
  file:
    path: "{{ vector_data_dir }}"
    state: directory
    owner: vector
    group: vector
    mode: '0755'
  become: true

- name: Deploy vector config
  template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    owner: vector
    group: vector
    mode: '0644'
  notify: Restart vector
  become: true

- name: Ensure vector is running and enabled
  systemd:
    name: vector
    state: started
    enabled: true
  become: true
