---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu_latest
    image: ubuntu:22.04
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3

provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: prepare.yml

verifier:
  name: ansible
